config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  # mobile redirect
  get '/mobileredirect' => 'home#mobile_redirect'

  # home controller
  root 'home#index'
  
  # auth
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users
  get '/users/:id' => 'users#show', :as => 'show_user'








  resources :climb_records
  resources :indexed_activities

  #reports
  get '/reports' => 'reports#index'
  get '/reports/annual_report' => 'reports#annual_report'

  get '/users/:id/index_activities' => 'users#index_activities'

  get '/summits/:id' => 'summits#show' 
  #get '/summits' => 'summits#index'

  get 'users/:id/elevation' => 'users#elevation'

  #osm api
  get '/osm/get_summits' => 'osm#get_summits'

  get '/users/connect/' => 'users#connect'

  # tabs
  get '/users/show' => 'users#show'
  get '/users/:id/map' => 'users#map'
  get '/users/:id/lists' => 'users#lists'
  get '/users/:id/vertical' => 'users#vertical'

  get '/users/:id/profile' => 'users#profile'
  get '/users' => 'users#index', as: 'users'
  get '/lists' => 'summit_list#index', as: 'lists'
  get '/lists/:id' => 'summit_list#show'
  get '/summits' => 'summits#index', as: 'summits'

  get '/users/get_summits/:id' => 'users#get_summits'
  get '/users/get_activities/:id' => 'users#get_activities'
  get '/users/get_activity/:id' => 'users#get_activity'
  get '/map_activities/:id' => 'users#map_activities'
  get '/users/get_status/:id' => 'users#get_status'
  get '/users/activity_count/:id' => 'users#activity_count'
  get '/users/indexed_count/:id' => 'users#indexed_count'
  get '/summit_lists' => 'summit_list#index'
  get '/scrape_peaks' => 'summit_list#scrape_peaks'
  resources :summit_completions


  #devise_for :users
  resources :users
end

app/models/climb_record.rb
class ClimbRecord < ActiveRecord::Base
  belongs_to :User
end

app/controllers/climb_records_controller.rb
class ClimbRecordsController < ApplicationController
  before_action :set_climb_record, only: [:show, :edit, :update, :destroy]

  # GET /climb_records
  # GET /climb_records.json
  def index
    @climb_records = ClimbRecord.all
  end

  # GET /climb_records/1
  # GET /climb_records/1.json
  def show
  end

  # GET /climb_records/new
  def new
    @climb_record = ClimbRecord.new
  end

  # GET /climb_records/1/edit
  def edit
  end

  # POST /climb_records
  # POST /climb_records.json
  def create
    @climb_record = ClimbRecord.new(climb_record_params)

    respond_to do |format|
      if @climb_record.save
        format.html { redirect_to @climb_record, notice: 'Climb record was successfully created.' }
        format.json { render :show, status: :created, location: @climb_record }
      else
        format.html { render :new }
        format.json { render json: @climb_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /climb_records/1
  # PATCH/PUT /climb_records/1.json
  def update
    respond_to do |format|
      if @climb_record.update(climb_record_params)
        format.html { redirect_to @climb_record, notice: 'Climb record was successfully updated.' }
        format.json { render :show, status: :ok, location: @climb_record }
      else
        format.html { render :edit }
        format.json { render json: @climb_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /climb_records/1
  # DELETE /climb_records/1.json
  def destroy
    @climb_record.destroy
    respond_to do |format|
      format.html { redirect_to climb_records_url, notice: 'Climb record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_climb_record
      @climb_record = ClimbRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def climb_record_params
      params.require(:climb_record).permit(:elevation_gain, :activity_id, :start_time, :end_time, :total_time, :User_id)
    end
end

app/helpers/climb_records_helper.rb
module ClimbRecordsHelper
end

app/views/climb_records/_form.html.erb
<%= form_for(@climb_record) do |f| %>
  <% if @climb_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@climb_record.errors.count, "error") %> prohibited this climb_record from being saved:</h2>

      <ul>
      <% @climb_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :elevation_gain %><br>
    <%= f.number_field :elevation_gain %>
  </div>
  <div class="field">
    <%= f.label :activity_id %><br>
    <%= f.number_field :activity_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.number_field :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.number_field :end_time %>
  </div>
  <div class="field">
    <%= f.label :total_time %><br>
    <%= f.number_field :total_time %>
  </div>
  <div class="field">
    <%= f.label :User_id %><br>
    <%= f.text_field :User_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/climb_records/edit.html.erb
<h1>Editing Climb Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @climb_record %> |
<%= link_to 'Back', climb_records_path %>

app/views/climb_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Climb Records</h1>

<table>
  <thead>
    <tr>
      <th>Elevation gain</th>
      <th>Activity</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Total time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @climb_records.each do |climb_record| %>
      <tr>
        <td><%= climb_record.elevation_gain %></td>
        <td><%= climb_record.activity_id %></td>
        <td><%= climb_record.start_time %></td>
        <td><%= climb_record.end_time %></td>
        <td><%= climb_record.total_time %></td>
        <td><%= climb_record.User %></td>
        <td><%= link_to 'Show', climb_record %></td>
        <td><%= link_to 'Edit', edit_climb_record_path(climb_record) %></td>
        <td><%= link_to 'Destroy', climb_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Climb record', new_climb_record_path %>

app/views/climb_records/new.html.erb
<h1>New Climb Record</h1>

<%= render 'form' %>

<%= link_to 'Back', climb_records_path %>

app/views/climb_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Elevation gain:</strong>
  <%= @climb_record.elevation_gain %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @climb_record.activity_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @climb_record.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @climb_record.end_time %>
</p>

<p>
  <strong>Total time:</strong>
  <%= @climb_record.total_time %>
</p>

<p>
  <strong>User:</strong>
  <%= @climb_record.User %>
</p>

<%= link_to 'Edit', edit_climb_record_path(@climb_record) %> |
<%= link_to 'Back', climb_records_path %>