config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  # mobile redirect
  get '/mobileredirect' => 'home#mobile_redirect'

  # home controller
  root 'home#index'
  
  # auth
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users
  get '/users/:id' => 'users#show', :as => 'show_user'








  resources :climb_records
  resources :indexed_activities

  #reports
  get '/reports' => 'reports#index'
  get '/reports/annual_report' => 'reports#annual_report'

  get '/users/:id/index_activities' => 'users#index_activities'

  get '/summits/:id' => 'summits#show' 
  #get '/summits' => 'summits#index'

  get 'users/:id/elevation' => 'users#elevation'

  #osm api
  get '/osm/get_summits' => 'osm#get_summits'

  get '/users/connect/' => 'users#connect'

  # tabs
  get '/users/show' => 'users#show'
  get '/users/:id/map' => 'users#map'
  get '/users/:id/lists' => 'users#lists'
  get '/users/:id/vertical' => 'users#vertical'

  get '/users/:id/profile' => 'users#profile'
  get '/users' => 'users#index', as: 'users'
  get '/lists' => 'summit_list#index', as: 'lists'
  get '/lists/:id' => 'summit_list#show'
  get '/summits' => 'summits#index', as: 'summits'

  get '/users/get_summits/:id' => 'users#get_summits'
  get '/users/get_activities/:id' => 'users#get_activities'
  get '/users/get_activity/:id' => 'users#get_activity'
  get '/map_activities/:id' => 'users#map_activities'
  get '/users/get_status/:id' => 'users#get_status'
  get '/users/activity_count/:id' => 'users#activity_count'
  get '/users/indexed_count/:id' => 'users#indexed_count'
  get '/summit_lists' => 'summit_list#index'
  get '/scrape_peaks' => 'summit_list#scrape_peaks'
  resources :summit_completions


  #devise_for :users
  resources :users
end

app/models/indexed_activity.rb
class IndexedActivity < ActiveRecord::Base
        belongs_to :user
end

app/controllers/indexed_activities_controller.rb
class IndexedActivitiesController < ApplicationController
  before_action :set_indexed_activity, only: [:show, :edit, :update, :destroy]

  # GET /indexed_activities
  # GET /indexed_activities.json
  def index
    @indexed_activities = IndexedActivity.all
  end

  # GET /indexed_activities/1
  # GET /indexed_activities/1.json
  def show
  end

  # GET /indexed_activities/new
  def new
    @indexed_activity = IndexedActivity.new
  end

  # GET /indexed_activities/1/edit
  def edit
  end

  # POST /indexed_activities
  # POST /indexed_activities.json
  def create
    @indexed_activity = IndexedActivity.new(indexed_activity_params)

    respond_to do |format|
      if @indexed_activity.save
        format.html { redirect_to @indexed_activity, notice: 'Indexed activity was successfully created.' }
        format.json { render :show, status: :created, location: @indexed_activity }
      else
        format.html { render :new }
        format.json { render json: @indexed_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indexed_activities/1
  # PATCH/PUT /indexed_activities/1.json
  def update
    respond_to do |format|
      if @indexed_activity.update(indexed_activity_params)
        format.html { redirect_to @indexed_activity, notice: 'Indexed activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @indexed_activity }
      else
        format.html { render :edit }
        format.json { render json: @indexed_activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indexed_activities/1
  # DELETE /indexed_activities/1.json
  def destroy
    @indexed_activity.destroy
    respond_to do |format|
      format.html { redirect_to indexed_activities_url, notice: 'Indexed activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indexed_activity
      @indexed_activity = IndexedActivity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def indexed_activity_params
      params.require(:indexed_activity).permit(:userId, :activityId)
    end
end

app/helpers/indexed_activities_helper.rb
module IndexedActivitiesHelper
end

app/views/indexed_activities/_form.html.erb
<%= form_for(@indexed_activity) do |f| %>
  <% if @indexed_activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indexed_activity.errors.count, "error") %> prohibited this indexed_activity from being saved:</h2>

      <ul>
      <% @indexed_activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userId %><br>
    <%= f.number_field :userId %>
  </div>
  <div class="field">
    <%= f.label :activityId %><br>
    <%= f.number_field :activityId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indexed_activities/edit.html.erb
<h1>Editing Indexed Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @indexed_activity %> |
<%= link_to 'Back', indexed_activities_path %>

app/views/indexed_activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Indexed Activities</h1>

<table>
  <thead>
    <tr>
      <th>Userid</th>
      <th>Activityid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @indexed_activities.each do |indexed_activity| %>
      <tr>
        <td><%= indexed_activity.userId %></td>
        <td><%= indexed_activity.activityId %></td>
        <td><%= link_to 'Show', indexed_activity %></td>
        <td><%= link_to 'Edit', edit_indexed_activity_path(indexed_activity) %></td>
        <td><%= link_to 'Destroy', indexed_activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Indexed activity', new_indexed_activity_path %>

app/views/indexed_activities/new.html.erb
<h1>New Indexed Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', indexed_activities_path %>

app/views/indexed_activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Userid:</strong>
  <%= @indexed_activity.userId %>
</p>

<p>
  <strong>Activityid:</strong>
  <%= @indexed_activity.activityId %>
</p>

<%= link_to 'Edit', edit_indexed_activity_path(@indexed_activity) %> |
<%= link_to 'Back', indexed_activities_path %>