config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  # mobile redirect
  get '/mobileredirect' => 'home#mobile_redirect'

  # home controller
  root 'home#index'
  
  # auth
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/auth/failure', to: redirect('/')

  # users
  get '/users/:id' => 'users#show', :as => 'show_user'








  resources :climb_records
  resources :indexed_activities

  #reports
  get '/reports' => 'reports#index'
  get '/reports/annual_report' => 'reports#annual_report'

  get '/users/:id/index_activities' => 'users#index_activities'

  get '/summits/:id' => 'summits#show' 
  #get '/summits' => 'summits#index'

  get 'users/:id/elevation' => 'users#elevation'

  #osm api
  get '/osm/get_summits' => 'osm#get_summits'

  get '/users/connect/' => 'users#connect'

  # tabs
  get '/users/show' => 'users#show'
  get '/users/:id/map' => 'users#map'
  get '/users/:id/lists' => 'users#lists'
  get '/users/:id/vertical' => 'users#vertical'

  get '/users/:id/profile' => 'users#profile'
  get '/users' => 'users#index', as: 'users'
  get '/lists' => 'summit_list#index', as: 'lists'
  get '/lists/:id' => 'summit_list#show'
  get '/summits' => 'summits#index', as: 'summits'

  get '/users/get_summits/:id' => 'users#get_summits'
  get '/users/get_activities/:id' => 'users#get_activities'
  get '/users/get_activity/:id' => 'users#get_activity'
  get '/map_activities/:id' => 'users#map_activities'
  get '/users/get_status/:id' => 'users#get_status'
  get '/users/activity_count/:id' => 'users#activity_count'
  get '/users/indexed_count/:id' => 'users#indexed_count'
  get '/summit_lists' => 'summit_list#index'
  get '/scrape_peaks' => 'summit_list#scrape_peaks'
  resources :summit_completions


  #devise_for :users
  resources :users
end

app/models/summit_completion.rb
class SummitCompletion < ActiveRecord::Base
    belongs_to :user
end

app/controllers/summit_completions_controller.rb
class SummitCompletionsController < ApplicationController
  before_action :set_summit_completion, only: [:show, :edit, :update, :destroy]

  # GET /summit_completions
  # GET /summit_completions.json
  def index
    @summit_completions = SummitCompletion.all
  end

  # GET /summit_completions/1
  # GET /summit_completions/1.json
  def show
  end

  # GET /summit_completions/new
  def new
    @summit_completion = SummitCompletion.new
  end

  # GET /summit_completions/1/edit
  def edit
  end

  # POST /summit_completions
  # POST /summit_completions.json
  def create
    @summit_completion = SummitCompletion.new(summit_completion_params)

    respond_to do |format|
      if @summit_completion.save
        format.html { redirect_to @summit_completion, notice: 'Summit completion was successfully created.' }
        format.json { render :show, status: :created, location: @summit_completion }
      else
        format.html { render :new }
        format.json { render json: @summit_completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /summit_completions/1
  # PATCH/PUT /summit_completions/1.json
  def update
    respond_to do |format|
      if @summit_completion.update(summit_completion_params)
        format.html { redirect_to @summit_completion, notice: 'Summit completion was successfully updated.' }
        format.json { render :show, status: :ok, location: @summit_completion }
      else
        format.html { render :edit }
        format.json { render json: @summit_completion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /summit_completions/1
  # DELETE /summit_completions/1.json
  def destroy
    @summit_completion.destroy
    respond_to do |format|
      format.html { redirect_to summit_completions_url, notice: 'Summit completion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_summit_completion
      @summit_completion = SummitCompletion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def summit_completion_params
      params.require(:summit_completion).permit(:summit, :userId)
    end
end

app/helpers/summit_completions_helper.rb
module SummitCompletionsHelper
end

app/views/summit_completions/_form.html.erb
<%= form_for(@summit_completion) do |f| %>
  <% if @summit_completion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summit_completion.errors.count, "error") %> prohibited this summit_completion from being saved:</h2>

      <ul>
      <% @summit_completion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :summit %><br>
    <%= f.text_field :summit %>
  </div>
  <div class="field">
    <%= f.label :userId %><br>
    <%= f.number_field :userId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/summit_completions/edit.html.erb
<h1>Editing Summit Completion</h1>

<%= render 'form' %>

<%= link_to 'Show', @summit_completion %> |
<%= link_to 'Back', summit_completions_path %>

app/views/summit_completions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Summit Completions</h1>

<table>
  <thead>
    <tr>
      <th>Summit</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @summit_completions.each do |summit_completion| %>
      <tr>
        <td><%= summit_completion.summit %></td>
        <td><%= summit_completion.userId %></td>
        <td><%= link_to 'Show', summit_completion %></td>
        <td><%= link_to 'Edit', edit_summit_completion_path(summit_completion) %></td>
        <td><%= link_to 'Destroy', summit_completion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Summit completion', new_summit_completion_path %>

app/views/summit_completions/new.html.erb
<h1>New Summit Completion</h1>

<%= render 'form' %>

<%= link_to 'Back', summit_completions_path %>

app/views/summit_completions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Summit:</strong>
  <%= @summit_completion.summit %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @summit_completion.userId %>
</p>

<%= link_to 'Edit', edit_summit_completion_path(@summit_completion) %> |
<%= link_to 'Back', summit_completions_path %>